[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd src/frontend && npm install"]

[phases.build]
cmds = ["cd src/frontend && npm run build"]

[start]
cmd = "cd src/frontend && npx serve -s build"
